### PR TITLE
Trying to fix Errors in _async_subscribe_for_data #347 

### LINKED ISSUE #338: Unknown Exception - 'list' object has no attribute 'object_key'
### The problem

Under v0.4.0b5 / HA 2024.6.3, every 5 minutes, the following error pops:

2024-06-17 19:21:10.772 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
2024-06-17 19:26:11.491 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
2024-06-17 19:31:12.226 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b5

### What version of Home Assistant Core has the issue?

2024.6.3

### Device / Model

_No response_

### Diagnostics information

_No response_

### Home Assistant log

<details><summary>Logs</summary>

```
2024-06-17 19:21:10.772 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
2024-06-17 19:26:11.491 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
2024-06-17 19:31:12.226 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
```
</details>

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by GSzabados**
I have managed to squash all the errors popping up from that _async_subscribe_for_data, but I am not sure that the main logic is correct in the code. If after this fix, it still generates high traffic to the Google servers, then the whole logic of subscribing is flawed somewhere.

To be honest, I don't understand what is meant to be achieved with this part of the code. It might be re-subscribing after each message received from Google, and that causes a lot of traffic. I cannot test the traffic issue, because I have only battery powered Nest protects.

It should fix #338 as well, as they are duplicates.

Fixes #338

### CODE REVIEW

**Comment by GSzabados** [comment]
@iMicknl, this would be more important to review, as this one causes the integration to hang for 5 minutes and then re-tries the status comes through and fails on the matching, as the input is not what it expects. Mainly was due to the [ ] wrapping (making it a single element list). But after removing the [ ], then the formatting fails for the nestpy client, so it has to wrapped with the bucket to have the right format.

As I noted, I don't really get the logic of the whole subscription, but it does go through and not fail on incorrect formatting. Someone should test it with wired nest projects which are sending multiple updates on motion.

Otherwise, if you would provide some details how the previous fix was putting a lot of load on the Google servers, then I might could understand where could be the issue for that.

**Comment by iMicknl** [comment]
@GSzabados I have to admit it is a long time since I wrote this integration. When a new event is pushed by Nest server, we have to register again and in this register step we have to send what we subscribe to and which values we received last. If we don't do this in the right way, it is increasing the load on the Nest protect server massively.

I introduced an error error when I started to add (better) typing to this integration, so most likely the culprit is there. In the original implementation (in the main branch) no issues have been reported. For me it is hard to debug if we are doing extra requests to Nest Protects server, thus that is something where I would need to add some additional logging.

**Comment by iMicknl** [comment]
If I am not mistaken, the code is adapted from https://github.com/chrisjshull/homebridge-nest/blob/master/lib/nest-connection.js#L1828.

**Comment by GSzabados** [comment]
That is a tough one, but I will have a look. I literally matched as the code was suggesting, and after the matching wrapped with the bucket(), so the format should be the same, otherwise, the client was failing on it.

How can you verify the additional load? What do you mean "the right way"?

**Comment by iMicknl** [comment]
Do you have Discord by any chance? If so, can you add me there? (`_imick`)?

**Comment by GSzabados** [comment]
Just messaged you.

**Comment by GSzabados** [comment]
I have had a look at the Buckets coming and going. They are the "same", but once the integration is (re)started the value={} in each bucket is sorted, and the order does not match with what the API sends, but the content looks the same.

Would that matter?

The other question, when re-subscribing, should it send back all the Buckets, or just the updated one? As I see from my code, it sends back (re-subscribes) to everything, not just the updated one.

**Comment by GSzabados** [comment]
As we discussed on Discord, the issue with the v0.4.6b fix was that it has not matched and merged the updated buckets, so it wa continuously sending back and old bucket for subscription and the API was replying with the current one, doing this in an endless loop.

This fix does the match and merge correctly and subscribes with the right updated bucket. 

I am running it at least for 3 weeks now and have not seen any error messages from the integration.

**Comment by genehand** [comment]
Running this code now as well. So far occupancy detection is quick again and I'm not seeing any errors in the log.

**Review by iMicknl — APPROVED** [review]
Great work! If you have additional time, would be good to figure out the root cause here. As discussed this is a good patch, but more a workaround for the errors, doesn't touch the root cause.

**Comment by GSzabados** [comment]
> doesn't touch the root cause

I think the root cause is the formatting. Objects vs Updated_Bucket. I think it should be the same format passed between the __init__.py and the client.py.


This is not correct as the `objects` is list of dicts, meanwhile `updated_buckets` a list of Bucket objects (disregarding that inside they are dicts)
`data.updated_buckets = objects`

It should be kept the same way either always as `objects`, or `updated_buckets`.

The issue with the WhereBucketValue is likely that it is formatted correctly, and the we do nothing with it, so it doesn't need re-casting as it is already WhereBucketValue object.

Hopefully I used correctly the terminology.

**Pull request merged**
