### PR TITLE
Use async_forward_entry_setups function

### PR DESCRIPTION
**Pull request by RobertD502**
- Utilize `async_forward_entry_setups` instead of `async_setup_platforms`

Starting with Home Assistant 2023.3, any integration using the old function will fail to start.

### CODE REVIEW

**Comment by RobertD502** [comment]
Thanks @iMicknl. Just a heads up: Starting with Home Assistant 2023.2, support for Python 3.9 is dropped so it may be worth while dropping building 3.9 in the tests / increasing the minimum requirement of HA to 2023.2 for the next release.

**Comment by iMicknl** [comment]
Makes sense, should also add Python 3.11 to CI/CD. Unfortunately I will be still very busy for 1 a 2 weeks, so it will be a bit delayed.

**Comment by RobertD502** [comment]
No rush at all. The integration won't break until 2023.3, so you have time.

**Comment by iMicknl** [comment]
Please rebase on main for fixed CI/CD.

**Pull request merged**
