### PR TITLE
Try to fix Unknown Exception - 'list' object has no attribute 'object…

### PR DESCRIPTION
**Pull request by iMicknl**
…_key' #338

### CODE REVIEW

**Comment by tbclark3** [comment]
I'm still getting the error.

**Comment by iMicknl** [comment]
@tbclark3 with this PR?

**Comment by tbclark3** [comment]
No, sorry!!  The latest beta came out about the same time as this PR and I mistakenly assumed that it was merged. I now see that it hasn't been. I will test it.

**Comment by tbclark3** [comment]
I'm still getting an error with this PR. Log below.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/__init__.py:170
integration: Nest Protect (documentation, issues)
First occurred: 4:56:02 PM (1 occurrences)
Last logged: 4:56:02 PM

Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 170, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/config/custom_components/nest_protect/pynest/client.py", line 288, in subscribe_for_data
    bucket = Bucket(**bucket)
  File "<string>", line 8, in __init__
  File "/config/custom_components/nest_protect/pynest/models.py", line 88, in __post_init__
    self.value = WhereBucketValue(**self.value)
                 ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: custom_components.nest_protect.pynest.models.WhereBucketValue() argument after ** must be a mapping, not WhereBucketValue

**Pull request closed without merging**
