### PR TITLE
Add boilerplate async_remove_config_entry_device so users can remove dead devices.

### PR DESCRIPTION
**Pull request by tomwilkie**
This will allow users to remove devices from HASS when its been removed from nest.

Unfortunately it will also allows users to remove active devices, but a quick reload puts them back.

Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>

### CODE REVIEW

**Comment by tomwilkie** [comment]
Fixes #130

**Comment by iMicknl** [comment]
Please rebase on main for fixed CI/CD.

**Comment by tomwilkie** [comment]
Thank you!

**Comment by mxr** [comment]
Thank you!

**Pull request merged**
