### PR TITLE
update TEMP_CELSIUS to UnitOfTemperature.CELSIUS

### PR DESCRIPTION
**Pull request by bmos**
This is _eventually_ going to be deprecated.

Closes issue #290

### CODE REVIEW

**Comment by Anto79-ops** [comment]
Did the changes manually, and it works. Thanks!

**Comment by bmos** [comment]
@iMicknl I didn't see any instructions for contributions, so I wasn't sure which branch to target this against.
Let me know if I should change it to main.

**Comment by iMicknl** [comment]
> @iMicknl I didn't see any instructions for contributions, so I wasn't sure which branch to target this against. Let me know if I should change it to main.

Beta is fine! I just need to check why CI/CD is broken again... Not related to your PR most likely 😉.

**Comment by bmos** [comment]
> > @iMicknl I didn't see any instructions for contributions, so I wasn't sure which branch to target this against. Let me know if I should change it to main.
> 
> Beta is fine! I just need to check why CI/CD is broken again... Not related to your PR most likely 😉.

In case this helps: https://pytest-asyncio.readthedocs.io/en/latest/index.html

**Comment by bmos** [comment]
It's still broken, but only 1 test fails if you add `asyncio_mode = auto` to pytest.ini.
https://github.com/bmos/ha-nest-protect/tree/patch-3

**Comment by bmos** [comment]
Ah! I see you had already found this on the beta branch
https://github.com/iMicknl/ha-nest-protect/pull/279/commits/b916f355fa0b5e39000523862c704f86b16de8df

**Comment by bmos** [comment]
It appears that you have already fixed the CI on the beta branch and it's just not being used :)

**Comment by bmos** [comment]
I'm going to recreate this PR based entirely on the beta branch so I can test with the corrected tests.

**Pull request closed without merging**
